spring.application.name=mongopersona
spring.mongodb.uri=mongodb+srv://241150050_db_user:YeFASWapDJceUIHU@itat.3qcd8lb.mongodb.net/itat?retryWrites=true&w=majority
spring.thymeleaf.cache=false
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
app.base-url=http://localhost:8080
