spring.application.name=mongopersona
spring.mongodb.uri=mongodb+srv://241150231_db_user:Y6ye1GWd92IEZ4FH@itat.3qcd8lb.mongodb.net/itat?retryWrites=true&w=majority
spring.thymeleaf.cache=false logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
app.base-url=http://localhost:8080
